// Original bug: KT-1858
// Duplicated bug: KT-1858

package perf1


fun main(args : Array<String>) {
    val res = args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +

    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +

    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +

    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +

    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +

    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +

    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
    args[0] + args[0] + args[0] + args[0] + args[0] + args[0] +
}